content: |-
  # ALZ.Connectivity

  This project deploys Azure Connectivity resources with an Azure Virtual WAN network topology into an existing subscription (Connectivity Subscription within the Platform Management Group) that has been created as part of the Enterprise Scale Core Management Group deployment.

  Azure Virtual WAN is a Microsoft-managed solution that provides end-to-end, global, and dynamic transit connectivity by default. Virtual WAN hubs eliminate the need to manually configure network connectivity. For example, you don't need to manage user-defined routes (UDR) or network virtual appliances (NVAs) to enable global transit connectivity. Virtual WAN simplifies end-to-end network connectivity in Azure, and to Azure from on-premises, by creating a hub-and-spoke network architecture. The architecture can easily scale to support multiple Azure regions and on-premises locations (any-to-any connectivity) as shown below:

  ![vwan](vwan.png)

  ## Updating Docs

  The `terraform-docs` utility is used to generate this README. Follow the below steps to update:
  1. Make changes to the `.terraform-docs.yml` file
  2. Fetch the `terraform-docs` binary (https://terraform-docs.io/user-guide/installation/)
  3. Run `terraform-docs markdown table --output-file ${PWD}/README.md --output-mode inject terraform/`

  ## Custom Route Tables

  In certain cases there may be a requirement where a Landing Zone requires the use of a custom defined route table with specific routes. This is supported by defining a Virtual Hub Route Table within this repository, which can then be referenced in the vnet configuration for a Landing Zone. Steps are outlined below:
  1. Modify the `settings.route-tables.tf` file to add a new Hub Route Table, for example:
  ```hcl
    {{ include "examples/settings.route-tables.tf" }}
  ```
  2. Merge and apply the changes.
  3. Re-run the `ALZ.Core` Pipeline, which will update the `output.custom_route_tables` output.
  4. Within `ALZ.LandingZones.<LZ-Type>`, update the `virtual_networks` configuration for a Landing Zone to point to the newly created Hub Route Table:
  ```hcl
    {{ include "examples/landing-zone-vnet.tf" }}
  ```
  5. Run the related Landing Zones pipeline to apply changes.

  {{ .Inputs }}

  {{ .Outputs }}
